### ISSUE TITLE
add ref type

### ISSUE THREAD

**Issue by MikePodgorniy** [iyegoroff/react-native-reanimated-swipeable-views#5]
Hello! Can you add some typing to build complex handlers?
I don't now how to do it right, simple way is merge types:   

```typescript
  readonly panGestureHandlerProps?: PanGestureHandlerProperties & {
    ref?: React.RefObject<PanGestureHandler>;
  };
```

https://github.com/iyegoroff/react-native-reanimated-swipeable-views/blob/a732311bc2e1d6e0badb2052261b564e0213084c/src/swipeable.tsx#L288

**Comment by iyegoroff** [comment]
Hi @MikePodgorniy!
I don't have enough time right now to revisit this. Feel free to resolve this in any fashion that works for you and open a PR.
